### ISSUE TITLE
Feature Request - Recalculate All Chunks When The Season Changes

### ISSUE THREAD

**Issue by DearreeD** [Straywave/ImmersiveSnow#3]
Great mod by the way, I just have a little suggestion for it.
From my knowledge and testing (ImmersiveSnow 1.2.0 with Fabric Seasons 1.4 on Minecraft 1.19.2), this mod doesn't recalculate loaded chunks when seasons change, so snow levels in spawn chunks and within a player's view distance aren't updated immediately. This usually creates harsh snow borders around the world spawn point and wherever players are at the time of seasons shifting (also means the permanently loaded spawn chunks never have their snow levels recalculated). My suggestion is to (perhaps as a config option) recalculate _all_ chunks when seasons change, even if they're currently loaded or still within the mod's "Memory Duration" from the config.
Regardless, thanks for creating this mod, it really makes the winter season more consistent.

**Comment by Straywave** [comment]
I'll look into it. The current solution is just to wait a bit or reload the world. Since all season mods have a different API, the current implementation is just a timer for chunks that is there to prevent lag. You can change timer duration via the "memoryDuration" config option to shorten the delay as a temporary workaround for now.

**Comment by DarkgreenWorld** [comment]
For example, in early spring, we only eliminate a portion of the snow, while the snow in the player's view gradually melts. In mid spring, all the snow in the player's view melts, while all the snow in other regions is eliminated.
